[package]
name = "advent-of-code-2021"
version = "0.1.0"
authors = ["Brian McDonald <bmcdonald916@gmail.com>"]
edition = "2018"

[[bin]]
name = "day-01"
path = "src/day-01.rs"

[[bin]]
name = "day-02"
path = "src/day-02.rs"